### ISSUE TITLE
Working configuration.yaml?

### ISSUE THREAD

**Issue by NonaSuomy** [wizmo2/TAudio-Case#1]
Hi is there a working version of the configuration.yaml for the current HomeAssistant?

**Comment by wizmo2** [comment]
Give me a couple of days and I'll work on it.  I think there are some better ways to do this now

**Comment by NonaSuomy** [comment]
Did they integrate your light stuff as well to master or just the DAC stuff, would I still need to use your code base to get the LED's working? Does the microphone work, and do you know if there is a manual way to input the LMS server's IP address into the esp32 so it knows where it is? My taudio on wifi and LMS docker are on two different subnets

**Comment by wizmo2** [comment]
The led control is still an open PR, so you would need my code base for that.  I'm a few releases behind. If you have an issue ,I can look at remerging.

Never tried it, but check out the squeezelite command-line options for setting the LMS IP address (Accessible in the Audio/Optional settings).   From a quick google, try -s <lms_ip>.  Otherwise, search the support page on the squeeze forum.  I'm sure this has come up before.

I don't believe the project supports audio-in or the microphone.  As a LMS client, there is no real requirement.  I think I did look at one point, but the quality pretty much sucked.

**Comment by NonaSuomy** [comment]
Ok, that would be great if you could do a remerge. Was there anything stopping them from merging your PR? can you link to it for me?

Thank you -s worked like a charm.

I just thought it would be cool if you could pass the mic into Home Assistant for audio controls (Alexa / Goog / or the open source projects) understandable though if LMS doesn't support that.

**Comment by wizmo2** [comment]
I've updated the configuration.yaml file.  It is only an example, and some of the entries may need to be pasted into other files (see notes).

**Comment by wizmo2** [comment]
As mentioned, I wasn't too impressed with the mic on this device.  I too, was looking at voice control.  In the end, I concluded it did not make sense.  If your going to use google or alexa, then you might as well use one of their devices.  If you're going down the open source solutions, then you'll need something more powerful than a ESP32.  I played around with Rhasspy and the 4-mic array, but again was not impressed.   

I'll look at remerging when I have time, although there is not much new, and none relates to the t-audio platform.  I did up a compiled release in my builds folder if you want to give it a try.

**Comment by NonaSuomy** [comment]
You’re awesome! Thanks will wait for that re-merge do you have a link to the past PR I can’t seem to find it. Wanted to see if they said anything about it etc? Maybe if resubmitted I could beg them to merge it.

I currently use the Alexa integration with HA and a Vector robot he has a 4 mic array on his back I believe not sure what they do differently but seems to work. https://www.digitaldreamlabs.com/products/vector-robot Got him for $80 on Amazon when the prior company was going under but too expensive now.

**Comment by NonaSuomy** [comment]
Is your binary compiling against the 4.3 branch?

**Comment by NonaSuomy** [comment]
Hope this helps, automations section was missing "trigger:" at the top and if you put input_text in its own yaml file you need to put quotes around the message: "{{ states('input_text.alert_trigger') }}"
  
configuration.yaml
```
# Loads default set of integrations. Do not remove.
default_config:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_text: !include input_text.yaml
input_number: !include input_number.yaml
notify: !include notify.yaml
light: !include light.yaml
```
light.yaml
```
# Squeezelite-esp32 T-Audio LED strip
- platform: template
  lights:
   taudio_good:
     friendly_name: "Notify Good"
     turn_on:
       service: squeezebox.call_method
       data:
         entity_id: media_player.squeezelite_taudio
         command: dmx
         parameters:
           - '0,80,0,0,80,0,0,80,0,0,80,0,0,80,0,0,80,0'
     turn_off:
       service: squeezebox.call_method
       data:
         entity_id: media_player.squeezelite_taudio
         command: dmx
         parameters:
           - '0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0'
   taudio_warn:
     friendly_name: "Notify Warn"
     turn_on:
       service: squeezebox.call_method
       data:
         entity_id: media_player.squeezelite_taudio
         command: dmx
         parameters:
           - '60,20,0,60,20,0,60,20,0,60,20,0,60,20,0'
           - '7'
     turn_off:
       service: squeezebox.call_method
       data:
         entity_id: media_player.squeezelite_taudio
         command: dmx
         parameters:
           - '0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0'
           - '7'
   taudio_alert:
     friendly_name: "Notify Alert"
     turn_on:
       service: squeezebox.call_method
       data:
         entity_id: media_player.squeezelite_taudio
         command: dmx
         parameters:
           - '80,0,0,80,0,0,80,0,0,80,0,0,80,0,0,80,0,0,80,0,0'
           - '12'
     turn_off:
       service: squeezebox.call_method
       data:
         entity_id: media_player.squeezelite_taudio
         command: dmx
         parameters:
           - '0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0'
           - '12'
   taudio_all:
      friendly_name: "TAudio Color"
      level_template: "{{states('input_number.taudio_l') | int(0)}}"
      value_template: "{{states('input_number.taudio_l') | int(0) > 0}}"
      color_template: "({{states('input_number.taudio_h') | int(0)}}, {{states('input_number.taudio_s') | int(0)}})"
      turn_on:
        - service: input_number.set_value
          data:
            entity_id: input_number.taudio_l
            value: '{{ state_attr("input_number.taudio_l","initial")|float(0) }}'
        - service: script.taudio_set
      turn_off:
        - service: input_number.set_value
          data:
            entity_id: input_number.taudio_l
            value: "0"
        - service: script.taudio_set
      set_level:
        - service: input_number.set_value
          data:
            value: "{{ brightness| float(0) }}"
            entity_id: input_number.taudio_l
        - service: script.taudio_set
      set_color:
        - service: input_number.set_value
          data:
            value: "{{ h }}"
            entity_id: input_number.taudio_h
        - service: input_number.set_value
          data:
            value: "{{ s }}"
            entity_id: input_number.taudio_s
        - service: script.taudio_set
```
automations.yaml
```
# Squeezelite-esp32 T-Audio Example TTS notify using an input text helper
- id: announce_to_speaker
  alias: TAudio Announce
  description: ''
  trigger:
  - platform: state
    entity_id: input_text.alert_trigger
  action:
  - service: squeezebox.call_method
    data:
      command: show
      parameters:
      - 'line1: HA Announce'
      - 'line2: {{ states("input_text.alert_trigger") }}'
      - 'font: light'
      - 'duration: 30'
    entity_id: media_player.squeezelite_taudio
  - service: notify.tts_announce
    data:
     message: "{{ states('input_text.alert_trigger') }}"
  mode: single
# Squeezelite-esp32 T-Audio the following automation uses text helpers to search and play music
- id: taudio_load_albums
  alias: taudio_load_albums
  description: ''
  trigger:
  - platform: state
    entity_id: input_text.taudio_play_albums
  condition: []
  action:
  - service: squeezebox.call_method
    data:
      entity_id: media_player.squeezelite_taudio
      command: playlist
      parameters:
        - loadtracks
        - 'album.titlesearch={{ states(''input_text.taudio_play_albums'') }}'
  mode: single
- id: taudio_load_artists
  alias: taudio_load_artists
  description: ''
  trigger:
  - platform: state
    entity_id: input_text.taudio_play_artists
  condition: []
  action:
  - service: squeezebox.call_method
    data:
      entity_id: media_player.squeezelite_taudio
      command: playlist
      parameters:
        - loadtracks
        - 'contributor.namesearch={{ states(''input_text.taudio_play_artists'') }}'
  mode: single
- id: taudio_load_songs
  alias: taudio_load_songs
  description: ''
  trigger:
  - platform: state
    entity_id: input_text.taudio_play_songs
  condition: []
  action:
  - service: squeezebox.call_method
    data:
      entity_id: media_player.squeezelite_taudio
      command: playlist
      parameters:
        - loadtracks
        - 'track.titlesearch={{ states(''input_text.taudio_play_songs'') }}'
  mode: single
```
scripts.yaml
```
# Squeezelite-ESP32 T-Audio Shared function to simplify template lights
taudio_set:
  alias: TAudio Set RGB Color
  sequence:
    - service: squeezebox.call_method
      data:
        entity_id: media_player.squeezelite_taudio
        command: dmx
        parameters:
          - '{% set gain = state_attr("light.taudio_all", "brightness")|int(0) %}{% for n in range(19) %}{% if gain == 0 %}0,0,0,{% else %}{% set rgb = state_attr("light.taudio_all", "rgb_color") %}{{ (rgb[0]|int(0) * gain / 255)|round  }},{{ (rgb[1]|int(0) * gain / 255)|round(0) }},{{ (rgb[2]|int(0) * gain / 255)|round(0) }},{% endif %}{% endfor %}'
          - "0"
# Squeezelite-esp32 T-Audio used to flash lights in service calls
taudio_alert_flash:
  alias: taudio_alert_flash
  sequence:
    repeat:
      count: 10
      sequence:
        - service: light.turn_on
          data:
            entity_id: light.taudio_alert
        - delay: '00:00:01'
        - service: light.turn_off
          data:
            entity_id: light.taudio_alert
        - delay: '00:00:03'
```
input_text.yaml
```
# Squeezelite-ESP32 T-Audio input_text
taudio_play_songs:
  name: "Play Songs"
taudio_play_artists:
  name: "Play Artist"
taudio_play_albums:
  name: "Play Album"
alert_trigger:
  name: "Alert Trigger Source"
```
input_number.yaml
```
# Squeezelite-ESP32 T-Audio input_number
taudio_h:
  name: TAudio Hue
  min: 0
  max: 360
taudio_s:
  name: TAudio Saturation
  min: 0
  max: 100
taudio_l:
  name: TAudio Level
  initial: 30
  min: 0
  max: 255
  step: 1
```
notify.yaml
```
# Squeezelite-ESP32 T-Audio a Text-To-Speech platform is required for the announcement to speaker example
- platform: tts
  name: tts_announce
  tts_service: tts.google_say
  media_player: media_player.squeezelite_taudio
```

**Comment by wizmo2** [comment]
Sorry - missed the last post.
Just updated merged with the master-cmake branch.  Have not looked at the 4.3 as yet,.  If it does get released as the default branch, I can taker a look, although there is no immediate need on the t-audio.

I just moved my server to the linux docker.  It was a pain to get the plugin updated to enable the LED control features. I ended up having to manually update the files on the server.  (which I think I had to do on the Windows integration too).

Thanks for the feedback.  I'll update the examples.

**Comment by NonaSuomy** [comment]
Even though you said the mic is not of great quality any chance you can add the wm8978 to the new audio code for home assistant - esphome? Seems to support media stuff a lot nicer than the squeeze stuff with HA.

https://github.com/esphome/media-players/blob/main/m5stack-atom-echo.yaml

They were first using the arduino framework then switched to esp-idf framework for esphome.
https://github.com/espressif/esp-adf/pull/33/files

https://github.com/esphome/esphome/tree/dev/esphome/components/i2s_audio

https://esphome.io/components/media_player/i2s_audio.html

https://rc.home-assistant.io/projects/thirteen-usd-voice-remote/

Example of another dac with i2c control for esphome.
https://github.com/esphome/esphome/pull/3552

Example YAML setup for muse-luxe

https://github.com/esphome/media-players/blob/main/raspiaudio-muse-luxe.yaml

Microphone example YAML

https://github.com/esphome/media-players/blob/main/m5stack-atom-echo.yaml

https://github.com/esphome/firmware/blob/91f781174ada31bd124c9ab5ef6f642720c3cb60/voice-assistant/m5stack-atom-echo.yaml

This is the echo YAML but pins swapped for the T-Audio 1.6 board.
https://github.com/LilyGO/TTGO-TAudio

Original Atom Echo YAML:

https://github.com/esphome/firmware/blob/91f781174ada31bd124c9ab5ef6f642720c3cb60/voice-assistant/m5stack-atom-echo.yaml

YAML could look something like this:
```yaml
# Substitute these words into the YAML below.
substitutions:
  name: "t-audio-001"
  friendly_name: "T-Audio-001"

# ESPHome Setup.
esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  min_version: 2023.5.0

# Board and Framework Setup.
esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

# Enable logging.
logger:

# Enable and set up the Home Assistant API.
api:
  encryption:
    key: !secret encryption_key005

# Enable OTA updates.
ota:
  password: !secret ota_pass005

# Enable and set up WiFi.
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: !secret use_address_wifi005

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: !secret fallbackhotspot005

# Enable captive portal if WiFi fails to connect.
captive_portal:

# Enable WebUI for direct control.
web_server:

# Configure the switch for restarting ESP32 from the WebUI.
switch:
  - platform: restart
    name: "${friendly_name} Restart"

# The improv_serial component in ESPHome implements the open Improv standard 
# for configuring Wi-Fi on an ESPHome device by using a serial connection to 
# the device, eg. USB.
improv_serial:

# Setup I2C pins for WM8978 communication.
i2c:
  sda: GPIO19
  scl: GPIO18

# Enable and set up the I2S audio pins.
i2s_audio:
  # Left / Right Clock or Word Select or Frame Sync.
  i2s_lrclk_pin: GPIO25
  # Bit Clock or Continuous Serial Clock [SCK].
  i2s_bclk_pin: GPIO33
  # Missing this pin setup?
  # Master Clock (typically 256 x LRCLK).
  #i2s_mclk_pin: 0

# Enable and set up the I2S microphone.
microphone:
  - platform: i2s_audio
    id: wm8978_microphone
    # Digital IN for the microphone.
    i2s_din_pin: GPIO27
    adc_type: external
    pdm: false

# Enable and set up the media player for TTS files to play.
media_player:
  - platform: i2s_audio
    name: "${friendly_name} I2SAudio"
    id: wm8978_audio
    dac_type: external
    # I2S Digital Out for speaker(s).
    i2s_dout_pin: GPIO26
    mode: stereo
    mute_pin:
      number: GPIO21
      inverted: true

# Enable and set up the WM8978 DAC.
# Need a wm8978 component.
#wm8978:

# Enable voice assistant.
voice_assistant:
  microphone: wm8978_microphone
  on_start:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        effect: none
  on_tts_start:
    - light.turn_on:
        id: led
        blue: 0%
        red: 0%
        green: 100%
        effect: none
  on_tts_end:
    - media_player.play_media: !lambda return x;
    - light.turn_on:
        id: led
        blue: 0%
        red: 0%
        green: 100%
        effect: none
    - media_player.play_media: !lambda return x;
  on_end:
    - delay: 1s
    - wait_until:
        not:
          media_player.is_playing: wm8978_audio
    - light.turn_off: led
  on_error:
    - light.turn_on:
        id: led
        blue: 0%
        red: 100%
        green: 0%
        effect: none
    - delay: 1s
    - light.turn_off: led

# The T-Audio Battery IC IP5306 is I2C so this code won't work.
#sensor:
#  - platform: adc
#    pin: GPIO??
#    name: Battery
#    icon: "mdi:battery-outline"
#    device_class: voltage
#    state_class: measurement
#    entity_category: diagnostic
#    unit_of_measurement: V
#    update_interval: 15s
#    accuracy_decimals: 3
#    attenuation: 11db
#    raw: true
#    filters:
#      - multiply: 0.00173913 # 2300 -> 4, for attenuation 11db, based on Olivier's code
#      - exponential_moving_average:
#          alpha: 0.2
#          send_every: 2
#      - delta: 0.002

# Enable and set up the volume and microphone capture buttons.
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO34
      inverted: true
      mode:
        input: true
        pullup: true
    name: Volume Up
    on_click:
      - media_player.volume_up: wm8978_audio
  - platform: gpio
    pin:
      number: GPIO36
      inverted: true
      mode:
        input: true
        pullup: true
    name: Volume Down
    on_click:
      - media_player.volume_down: wm8978_audio
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
      mode:
        input: true
        pullup: true
    name: Action
    on_multi_click:
      - timing:
          - ON FOR AT MOST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - media_player.toggle: wm8978_audio
      - timing:
          - ON FOR AT LEAST 350ms
        then:
          - voice_assistant.start:
      - timing:
          - ON FOR AT LEAST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - voice_assistant.stop:

# Enable and set up the 19 addressable LED's on the T-Audio 1.6.
light:
  - platform: fastled_clockless
    id: led
    name: "${friendly_name} LED(s)"
    disabled_by_default: true
    entity_category: config
    pin: GPIO22
    default_transition_length: 0s
    chipset: WS2812B
    num_leds: 19
    rgb_order: GRB
    rmt_channel: 0
    effects:
      - pulse:
          transition_length: 250ms
          update_interval: 250ms
```

It basically works (Button and LED haha) besides the wm8978 initialization code missing to turn off SOFTMUTE and enable the right and left audio channels.

Testing the button press (Doesn't detect audio from the microphone):
```
ESPHome version 2023.4.2 compiled on May  1 2023, 23:03:49
[23:04:23][D][api.connection:961]: Home Assistant 2023.5.0b5 (10.0.1.42): Connected successfully
[23:04:44][D][binary_sensor:036]: 'T-Audio-001 Button': Sending state ON
[23:04:44][D][voice_assistant:065]: Requesting start...
[23:04:44][D][voice_assistant:045]: Starting...
[23:04:44][D][voice_assistant:083]: Assist Pipeline running
[23:04:45][D][binary_sensor:036]: 'T-Audio-001 Button': Sending state OFF
[23:04:45][D][voice_assistant:073]: Signaling stop...
[23:04:53][E][voice_assistant:145]: Error: stt-no-text-recognized - No text recognized
```

Test sending a TTS wav file from Piper Docker in Home Assistant Docker with Wyoming Protocol (Doesn't output any sound).
```
[23:25:31][D][media_player:059]: 'T-Audio-001' - Setting
[23:25:31][D][media_player:066]:   Media URL: http://10.0.1.42:8123/api/tts_proxy/7b031c3d673c84477529b838252c3609e5be34b8_en-us_a877e2b3bf_tts.piper.wav
```

A bunch of docker-compose YAML I use for Home Assistant, Faster-Whisper, Piper, etc.
https://github.com/NonaSuomy/nonasuomy.github.io/blob/master/_posts/2022-10-15-docker.md

Seems they hardcode GPIO0 for the clock.

https://github.com/esphome/esphome/pull/3552/commits/b1ad48c8240707eae18e4b7b9266c3c3ee01b239
```c++
namespace es8388 {

void ES8388Component::setup() {
  PIN_FUNC_SELECT(PERIPHS_IO_MUX_GPIO0_U, FUNC_GPIO0_CLK_OUT1);
  WRITE_PERI_REG(PIN_CTRL, READ_PERI_REG(PIN_CTRL) & 0xFFFFFFF0);
```

https://github.com/esphome/esphome/tree/fcf0761ba3ed1647b19ecbcb6ddcd7e2f5c0932c/esphome/components/es8388
